### ISSUE TITLE
[BUG] Not compatible with Paper 588+ due to mysql-connector-java update

### ISSUE THREAD

**Issue by Codeloper** [brainsynder-Dev/SimplePets#104]
PaperMC updated mysql-connector-java to version 8.0.23 (https://github.com/PaperMC/Paper/pull/5474)

Since then the plugin doesn't start:
```
[13:24:24] [Server thread/ERROR]: Error occurred while enabling SimplePets v4.4 (build 55) (Is it up to date?)
java.lang.NoClassDefFoundError: com/mysql/jdbc/jdbc2/optional/MysqlDataSource
	at simplepets.brainsynder.database.MySQL.<init>(MySQL.java:16) ~[?:?]
	at simplepets.brainsynder.PetCore.handleSQL(PetCore.java:225) ~[?:?]
	at simplepets.brainsynder.PetCore.onEnable(PetCore.java:125) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-590]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-590]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-590]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-590]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-590]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-590]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-590]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-590]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 13 more
```

Running on Java 11.0.9+7-LTS

**Comment by Thatsmusic99** [comment]
[Man, I remember this.](https://github.com/Thatsmusic99/HeadsPlus/pull/24) Have reproduced on Paper Build 590 and SimplePets build 65, will investigate further to check workarounds.

**Comment by Thatsmusic99** [comment]
Should be patched in the [latest developer build.](https://ci.pluginwiki.us/job/SimplePets-Experimental/67/)

**Comment by Codeloper** [comment]
Works just fine, thank you for the fast fix!
