### ISSUE TITLE
[BUG] Mysql does not keep inventory

### ISSUE THREAD

**Issue by JavierPM87** [brainsynder-Dev/SimplePets#107]
Please drop the Debug.json file generated from doing `/pet debug` here
[debug.txt](https://github.com/brainsynder-Dev/SimplePets/files/6477957/debug.txt)

**Describe the bug**
Pet inventory is not saved when exiting the server

**Steps to reproduce**
1-I take out a pet
2-Open your inventory
3-I keep items in inventory
4-I close the inventory
5-I quit the server
6-I enter the server
7-I remove a pet (it seems that it also fails when you enter the server that the pet appears if you have not removed it before leaving)
-Open your inventory
-The saved items are not

**Expected behavior**
-That when entering the server you have in the pet's inventory what you saved before leaving the server

**Screenshots/Videos (If you have any)**

**Additional Information**
Add any other context about the problem here?
Hi! For a few days, I have noticed that when you save something in the pet's inventory, when leaving the server, it is not saved and the items are lost, a few days ago it worked, but when I changed hosting I have noticed this problem. Is it possible that it is because of the quote? use utf8mb4_unicode_ci

[11:25:47 INFO]: HappyTomo lost connection: Disconnected
[11:25:47 INFO]: [SimplePets Debug] Unable to save HappyTomo's Pet data.
[11:25:47 INFO]: [SimplePets Debug] Data that failed to save: 
[11:25:47 INFO]: [SimplePets Debug] - Name:HappyTomo
[11:25:47 INFO]: [SimplePets Debug] - UUID:994f760e-5c68-415b-b022-26962627a500
[11:25:47 INFO]: [SimplePets Debug] - PetName (Base64):ZW1wdHk=
[11:25:47 INFO]: [SimplePets Debug] - PetData:{}
[11:25:47 INFO]: [SimplePets Debug] - PurchasedPets (Base64):W10=
[11:25:47 INFO]: [SimplePets Debug] - Error:
[11:25:47 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
[11:25:47 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:25:47 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[11:25:47 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:25:47 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[11:25:47 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
[11:25:47 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:386)
[11:25:47 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
[11:25:47 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[11:25:47 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[11:25:47 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[11:25:47 WARN]:        at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1182)
[11:25:47 WARN]:        at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1177)
[11:25:47 WARN]:        at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4037)
[11:25:47 WARN]:        at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4006)
[11:25:47 WARN]:        at simplepets.brainsynder.player.MySQLHandler.lambda$save$1(MySQLHandler.java:65)
[11:25:47 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
[11:25:47 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
[11:25:47 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[11:25:47 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[11:25:47 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[11:25:47 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[11:25:47 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[11:25:47 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
[11:25:47 WARN]: 
[11:25:47 WARN]: The last packet successfully received from the server was 7,153,572 milliseconds ago.  The last packet sent successfully to the server was 978,629 milliseconds ago.
[11:25:47 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:25:47 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[11:25:47 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:25:47 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[11:25:47 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
[11:25:47 WARN]:        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[11:25:47 WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3517)
[11:25:47 WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3417)
[11:25:47 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3860)
[11:25:47 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[11:25:47 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[11:25:47 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[11:25:47 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
[11:25:47 WARN]:        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2023)
[11:25:47 WARN]:        at simplepets.brainsynder.player.MySQLHandler.lambda$load$2(MySQLHandler.java:123)
[11:25:47 WARN]:        ... 7 more
[11:25:47 WARN]: Caused by: java.net.SocketException: Connection timed out (Read failed)
[11:25:47 WARN]:        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
[11:25:47 WARN]:        at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
[11:25:47 WARN]:        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
[11:25:47 WARN]:        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
[11:25:47 WARN]:        at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
[11:25:47 WARN]:        at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144)
[11:25:47 WARN]:        at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
[11:25:47 WARN]:        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2966)
[11:25:47 WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3427)

[11:31:18 INFO]: UUID of player HappyTomo is 994f760e-5c68-415b-b022-26962627a500
[11:31:18 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
[11:31:18 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:31:18 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[11:31:18 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:31:18 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[11:31:18 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
[11:31:18 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:386)
[11:31:18 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
[11:31:18 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[11:31:18 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[11:31:18 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[11:31:18 WARN]:        at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1182)
[11:31:18 WARN]:        at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1177)
[11:31:18 WARN]:        at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4037)
[11:31:18 WARN]:        at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4006)
[11:31:18 WARN]:        at simplepets.brainsynder.player.MySQLHandler.lambda$load$2(MySQLHandler.java:121)
[11:31:18 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
[11:31:18 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
[11:31:18 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[11:31:18 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[11:31:18 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[11:31:18 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[11:31:18 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[11:31:18 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
[11:31:18 WARN]: 
[11:31:18 WARN]: The last packet successfully received from the server was 7,153,572 milliseconds ago.  The last packet sent successfully to the server was 978,629 milliseconds ago.
[11:31:18 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:31:18 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:31:18 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[11:31:18 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
[11:31:18 WARN]:        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[11:31:18 WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3517)
[11:31:18 WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3417)
[11:31:18 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3860)
[11:31:18 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[11:31:18 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[11:31:18 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[11:31:18 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
[11:31:18 WARN]:        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2023)
[11:31:18 WARN]:        at simplepets.brainsynder.player.MySQLHandler.lambda$load$2(MySQLHandler.java:123)
[11:31:18 WARN]:        ... 7 more
[11:31:18 WARN]: Caused by: java.net.SocketException: Connection timed out (Read failed)
[11:31:18 WARN]:        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
[11:31:18 WARN]:        at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
[11:31:18 WARN]:        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
[11:31:18 WARN]:        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
[11:31:18 WARN]:        at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
[11:31:18 WARN]:        at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144)
[11:31:18 WARN]:        at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
[11:31:18 WARN]:        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2966)
[11:31:18 WARN]:        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3427)
[11:31:18 WARN]:        ... 15 more
[11:31:18 INFO]: HappyTomo[/93.176.159.45:63677] logged in with entity id 250527 at ([world]65.69775223626958, 107.0, -39.20994638898123)
[11:31:18 INFO]: [SimplePets Debug] Unable to load HappyTomo's Pet data.
[11:25:47 WARN]:        ... 15 more

**Comment by luizsusin** [comment]
One month since this report and there's not an update? I understand that v5 must come out since 1.17 has already been released, but it doesn't seen like it's quite a difficult thing to fix.
Will v5 be able to load old SimplePets database? Is there any ETA?

**Comment by Thatsmusic99** [comment]
v5 does not currently have inventory support and we are debating on separating it into an addon regardless.

**Comment by brainsynder-Dev** [comment]
v5 will be able to read the old data, currently v5 is in a beta stage atm. still need to iron out any bugs and keep adding addons

**Comment by brainsynder-Dev** [comment]
This issue has been marked as stale due to the lack of response on it. If this problem is still occurring, please comment saying so or the issue will be closed in 7 days.
