### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by James-Cotterill** [brainsynder-Dev/SimplePets#108]
Please drop the Debug.json file generated from doing `/pet debug` here

**Describe the bug**
Upgraded to Java 16 and the plugin no longer works. Red status in /plugins

**Expected behavior**
Run

**Screenshots/Videos (If you have any)**
![image](https://user-images.githubusercontent.com/76694654/118706999-ec19ca00-b811-11eb-96f9-12c036f106c4.png)

**Comment by James-Cotterill** [comment]
[19:29:43] [Server thread/INFO]: [SimplePets] Enabling SimplePets v4.4 (build 47)
[19:29:44] [Server thread/ERROR]: Error occurred while enabling SimplePets v4.4 (build 47) (Is it up to date?)
java.lang.NoClassDefFoundError: com/mysql/jdbc/jdbc2/optional/MysqlDataSource
	at simplepets.brainsynder.database.MySQL.<init>(MySQL.java:16) ~[?:?]
	at simplepets.brainsynder.PetCore.handleSQL(PetCore.java:225) ~[?:?]
	at simplepets.brainsynder.PetCore.onEnable(PetCore.java:125) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-703]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.16.5.jar:git-Paper-703]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-703]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-703]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-703]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591) ~[patched_1.16.5.jar:git-Paper-703]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Paper-703]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066) ~[patched_1.16.5.jar:git-Paper-703]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-703]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.16.5.jar:git-Paper-703]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-703]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 13 more
[19:29:44] [Server thread/INFO]: [SimplePets] Disabling SimplePets v4.4 (build 47)

**Comment by Thatsmusic99** [comment]
[Your build is outdated.](https://ci.pluginwiki.us/job/SimplePets-Experimental/69/) Please try it with this one.

**Comment by James-Cotterill** [comment]
Wow... super quick response and working like a charm! Thank you so much :)
