### ISSUE TITLE
[Bug]: Error when going into Spectator Mode

### ISSUE THREAD

**Issue by brainsynder-Dev** [brainsynder-Dev/SimplePets#134]
### Debug Log

https://www.pastelog.us/ewurezidad

### What happened?

Theosis Said: "if I go into spectator mode with a pet out, the pet disappears and I get this exception: https://pastebin.com/300jAMXH "

### Steps To Reproduce

1. Summon Pet
2. Go into Spectator
3. Pet vanishes
4. Error outputs

### Relevant log/error output

```shell
[30.12 11:38:38] [Server] [ERROR] Entity threw exception at main:-0.5095730589734194,63.0,13.452276869424379
[30.12 11:38:38] [Server] java.lang.NoClassDefFoundErrorsimplepets/brainsynder/internal/apache/lang/reflect/FieldUtils
[30.12 11:38:38] [Server] 	at simplepets.brainsynder.versions.v1_18_R1.entity.EntityPet.handleInvisible(EntityPet.java:556) ~[SimplePets-1.18.1.jar:?]
[30.12 11:38:38] [Server] 	at simplepets.brainsynder.versions.v1_18_R1.entity.EntityPet.glowHandler(EntityPet.java:545) ~[SimplePets-1.18.1.jar:?]
[30.12 11:38:38] [Server] 	at simplepets.brainsynder.versions.v1_18_R1.entity.EntityPet.k(EntityPet.java:483) ~[SimplePets-1.18.1.jar:?]
[30.12 11:38:38] [Server] 	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1128) ~[?:?]
[30.12 11:38:38] [Server] 	at net.minecraft.world.level.Level.guardEntityTick(Level.java:970) ~[?:?]
[30.12 11:38:38] [Server] 	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:670) ~[?:?]
[30.12 11:38:38] [Server] 	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.1.jar:git-Paper-108]
[30.12 11:38:38] [Server] 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]
[30.12 11:38:38] [Server] 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-108]
[30.12 11:38:38] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-108]
[30.12 11:38:38] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-108]
[30.12 11:38:38] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-108]
[30.12 11:38:38] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-108]
[30.12 11:38:38] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[30.12 11:38:38] [Server] Caused byjava.lang.ClassNotFoundException: simplepets.brainsynder.internal.apache.lang.reflect.FieldUtils
[30.12 11:38:38] [Server] 	... more
```

### Up-To-Date

- [X] I am using the latest build

**Comment by brainsynder-Dev** [comment]
Was fixed in [build: 112](https://ci.pluginwiki.us/job/SimplePets_v5/112/)
