### ISSUE TITLE
[Bug]: Error when going into Vanish

### ISSUE THREAD

**Issue by brainsynder-Dev** [brainsynder-Dev/SimplePets#135]
### Debug Log

https://www.pastelog.us/ewurezidad

### What happened?

Aaimal Said: "I get an error when going into `/vanish`"

### Steps To Reproduce

1. Summon Pet
2. Type `/vanish`
3. Pet vanishes
4. Error gets output into Console

### Relevant log/error output

```shell
[12:12:09 ERROR]: Entity threw exception at world:-0.5016886729006815,64.0,-11.82345043718766
java.lang.NoClassDefFoundError: simplepets/brainsynder/internal/apache/lang/reflect/FieldUtils
        at simplepets.brainsynder.versions.v1_18_R1.entity.EntityPet.handleInvisible(EntityPet.java:559) ~[SimplePets-1.18.1.jar:?]
        at simplepets.brainsynder.versions.v1_18_R1.entity.EntityPet.glowHandler(EntityPet.java:548) ~[SimplePets-1.18.1.jar:?]
        at simplepets.brainsynder.versions.v1_18_R1.entity.EntityPet.k(EntityPet.java:486) ~[SimplePets-1.18.1.jar:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1128) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:970) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:670) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.1.jar:git-Paper-73]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-73]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-73]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-73]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-73]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-73]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: simplepets.brainsynder.internal.apache.lang.reflect.FieldUtils
        ... 14 more
```

### Up-To-Date

- [X] I am using the latest build

**Comment by brainsynder-Dev** [comment]
Was fixed in [build: 112](https://ci.pluginwiki.us/job/SimplePets_v5/112/)
