### ISSUE TITLE
[Bug]: You can't spawn pets in the air

### ISSUE THREAD

**Issue by Nononitas** [brainsynder-Dev/SimplePets#170]
### Debug Log

https://www.pastelog.us/uzunivozoz

### What happened?

If you fly and try to summon a pet you will get an error

### Relevant log/error output

```shell
[SimplePets] Task #42920 for SimplePets v5.0-BUILD-159 generated an exception
java.lang.NullPointerException: Cannot invoke "java.util.Map$Entry.getValue()" because the return value of "java.util.NavigableMap.ceilingEntry(Object)" is null
	at lib.brainsynder.storage.RandomCollection.next(RandomCollection.java:56) ~[SimplePets-1.17.1.jar:?]
	at simplepets.brainsynder.versions.v1_17_1.SpawnerUtil.getRandomLocation(SpawnerUtil.java:165) ~[SimplePets-1.17.1.jar:?]
	at simplepets.brainsynder.versions.v1_17_1.SpawnerUtil.spawnEntityPet(SpawnerUtil.java:72) ~[SimplePets-1.17.1.jar:?]
	at simplepets.brainsynder.utils.Utilities.handlePetSpawning(Utilities.java:106) ~[SimplePets-1.17.1.jar:?]
	at simplepets.brainsynder.listeners.SelectionGUIListener$1.run(SelectionGUIListener.java:76) ~[SimplePets-1.17.1.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Pufferfish-21]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Pufferfish-21]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1569) ~[patched_1.17.1.jar:git-Pufferfish-21]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:495) ~[patched_1.17.1.jar:git-Pufferfish-21]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1485) ~[patched_1.17.1.jar:git-Pufferfish-21]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1284) ~[patched_1.17.1.jar:git-Pufferfish-21]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Pufferfish-21]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Up-To-Date

- [X] I am using the latest build

**Comment by brainsynder-Dev** [comment]
I have been able to reproduce this, will work on a fix
