### ISSUE TITLE
[Bug]: 1.20.4 pets no spawn

### ISSUE THREAD

**Issue by thiagogebrimm** [brainsynder-Dev/SimplePets#256]
### Debug Log

https://pastebin.com/2H3uLGdn

### What happened?

When I try to summon a pet it says it is not possible and sends this error to the console.
```
>....java.lang.ClassCastException: class simplepets.brainsynder.versions.v1_20_4.entity.list.EntityAllayPet cannot be cast to class net.minecraft.world.entity.animal.allay.Allay (simplepets.brainsynder.versions.v1_20_4.entity.list.EntityAllayPet is in unnamed module of loader 'SimplePets.jar' @4cc6f62d; net.minecraft.world.entity.animal.allay.Allay is in unnamed module of loader java.net.URLClassLoader @e2144e4)
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.getEntity(CraftEntity.java:121)
        at net.minecraft.world.entity.Entity.getBukkitEntity(Entity.java:253)
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:795)
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:701)
        at net.minecraft.server.level.WorldServer.addEntity(WorldServer.java:1797)
        at net.minecraft.server.level.WorldServer.addFreshEntity(WorldServer.java:1705)
        at SimplePets.jar//simplepets.brainsynder.versions.v1_20_4.VersionTranslator.addEntity(VersionTranslator.java:96)
        at SimplePets.jar//simplepets.brainsynder.versions.v1_20_4.SpawnerUtil.spawnEntityPet(SpawnerUtil.java:120)
        at SimplePets.jar//simplepets.brainsynder.versions.v1_20_4.SpawnerUtil.spawnEntityPet(SpawnerUtil.java:70)
        at SimplePets.jar//simplepets.brainsynder.utils.Utilities.handlePetSpawning(Utilities.java:98)
        at SimplePets.jar//simplepets.brainsynder.listeners.SelectionGUIListener$1.run(SelectionGUIListener.java:76)
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1666)
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1545)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1235)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

### Up-To-Date

- [X] I am using the latest build

**Comment by Thatsmusic99** [comment]
Has been fixed in this Jenkins build: https://ci.pluginwiki.us/job/SimplePets_v5/234/
