### ISSUE TITLE
[Bug]: Error when using Purpur build 2014 for MC: 1.20.1

### ISSUE THREAD

**Issue by elkoyofficial** [brainsynder-Dev/SimplePets#259]
### Debug Log

https://www.pastelog.us/paste/IDCHKAJFGEB

### What happened?

Spam in chat when spawning a pet.

### Steps To Reproduce

1. Download SimplePets
2. Spawn a pet
version: purpur 1.20.1

### Relevant log/error output

```shell
[19:29:04 INFO]: [GlowingEntities] [GlowingEntities] Loaded mappings V1_20
[19:29:04 ERROR]: Could not pass event CreatureSpawnEvent to WorldGuard v7.0.9-beta1+2249-223b80c
java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because the return value of "org.bukkit.entity.EntityType.getName()" is null
        at com.fastasyncworldedit.bukkit.adapter.IBukkitAdapter.adapt(IBukkitAdapter.java:346) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-486.jar:?]
        at com.fastasyncworldedit.bukkit.adapter.IDelegateBukkitImplAdapter.adapt(IDelegateBukkitImplAdapter.java:271) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-486.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:395) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-486.jar:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardEntityListener.onCreatureSpawn(WorldGuardEntityListener.java:627) ~[worldguard-bukkit-7.0.9-beta1(1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor88.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2014]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:770) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:675) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1739) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1647) ~[?:?]
        at simplepets.brainsynder.versions.v1_20_1.VersionTranslator.addEntity(VersionTranslator.java:84) ~[SimplePets(1).jar:?]
        at simplepets.brainsynder.versions.v1_20_1.SpawnerUtil.spawnEntityPet(SpawnerUtil.java:120) ~[SimplePets(1).jar:?]
        at simplepets.brainsynder.versions.v1_20_1.SpawnerUtil.spawnEntityPet(SpawnerUtil.java:70) ~[SimplePets(1).jar:?]
        at simplepets.brainsynder.impl.PetOwner$1.lambda$run$5(PetOwner.java:120) ~[SimplePets(1).jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at simplepets.brainsynder.impl.PetOwner$1.lambda$run$6(PetOwner.java:113) ~[SimplePets(1).jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at simplepets.brainsynder.impl.PetOwner$1.lambda$run$7(PetOwner.java:112) ~[SimplePets(1).jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at simplepets.brainsynder.impl.PetOwner$1.run(PetOwner.java:109) ~[SimplePets(1).jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1507) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[19:29:04 ERROR]: Could not pass event CreatureSpawnEvent to WorldGuard v7.0.9-beta1+2249-223b80c
java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because the return value of "org.bukkit.entity.EntityType.getName()" is null
        at com.fastasyncworldedit.bukkit.adapter.IBukkitAdapter.adapt(IBukkitAdapter.java:346) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-486.jar:?]
        at com.fastasyncworldedit.bukkit.adapter.IDelegateBukkitImplAdapter.adapt(IDelegateBukkitImplAdapter.java:271) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-486.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:395) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-486.jar:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardEntityListener.onCreatureSpawn(WorldGuardEntityListener.java:627) ~[worldguard-bukkit-7.0.9-beta1(1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor88.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2014]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:770) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:675) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1739) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1647) ~[?:?]
        at simplepets.brainsynder.versions.v1_20_1.VersionTranslator.addEntity(VersionTranslator.java:84) ~[SimplePets(1).jar:?]
        at simplepets.brainsynder.versions.v1_20_1.SpawnerUtil.spawnEntityPet(SpawnerUtil.java:120) ~[SimplePets(1).jar:?]
        at simplepets.brainsynder.versions.v1_20_1.SpawnerUtil.spawnEntityPet(SpawnerUtil.java:70) ~[SimplePets(1).jar:?]
        at simplepets.brainsynder.impl.PetOwner$1.lambda$run$5(PetOwner.java:120) ~[SimplePets(1).jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at simplepets.brainsynder.impl.PetOwner$1.lambda$run$6(PetOwner.java:113) ~[SimplePets(1).jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at simplepets.brainsynder.impl.PetOwner$1.lambda$run$7(PetOwner.java:112) ~[SimplePets(1).jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at simplepets.brainsynder.impl.PetOwner$1.run(PetOwner.java:109) ~[SimplePets(1).jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1507) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2014]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Up-To-Date

- [X] I am using the latest build

**Comment by brainsynder-Dev** [comment]
I just tested on my test server using Purpur-2057 (MC: 1.20.1) and i do not get the error.
If possible test it on your end on a newer version of Purpur
