### ISSUE TITLE
[Bug]: ???

### ISSUE THREAD

**Issue by lajczik** [brainsynder-Dev/SimplePets#266]
### Debug Log

plugin disabled

### What happened?

plugin disabled
![image](https://github.com/brainsynder-Dev/SimplePets/assets/55200929/08b7f4f7-59ee-4ba0-b440-e345453886bd)

### Steps To Reproduce

1. load server via leaf paper 1.20.4 ~ https://github.com/Winds-Studio/Leaf

### Relevant log/error output

```shell
[10:31:40 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'SimplePets (5.0-build-257).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[leaf-1.20.4.jar:git-Leaf-"dd62783"]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[leaf-1.20.4.jar:git-Leaf-"dd62783"]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[leaf-1.20.4.jar:git-Leaf-"dd62783"]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[leaf-1.20.4.jar:git-Leaf-"dd62783"]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[leaf-1.20.4.jar:git-Leaf-"dd62783"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:529) ~[leaf-1.20.4.jar:git-Leaf-"dd62783"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:318) ~[leaf-1.20.4.jar:git-Leaf-"dd62783"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1138) ~[leaf-1.20.4.jar:git-Leaf-"dd62783"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:308) ~[leaf-1.20.4.jar:git-Leaf-"dd62783"]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[leaf-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[leaf-1.20.4.jar:git-Leaf-"dd62783"]
        ... 9 more
Caused by: java.lang.NumberFormatException: For input string: "Leaf"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.base/java.lang.Integer.parseInt(Integer.java:662) ~[?:?]
        at java.base/java.lang.Integer.parseInt(Integer.java:778) ~[?:?]
        at SimplePets (5.0-build-257).jar/simplepets.brainsynder.PetCore$ServerInformation.<init>(PetCore.java:669) ~[SimplePets (5.0-build-257).jar:?]
        at SimplePets (5.0-build-257).jar/simplepets.brainsynder.PetCore.<clinit>(PetCore.java:65) ~[SimplePets (5.0-build-257).jar:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[leaf-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[leaf-1.20.4.jar:git-Leaf-"dd62783"]
        ... 9 more
```

### Up-To-Date

- [X] I am using the latest build

**Comment by brainsynder-Dev** [comment]
Please update your SimplePets version from our [JENKINS](https://ci.bsdevelopment.org/job/SimplePets_v5/)
