### ISSUE TITLE
[Bug]: can't name pets

### ISSUE THREAD

**Issue by ichibanS** [brainsynder-Dev/SimplePets#277]
### Debug Log

https://www.pastelog.us/paste/AGKJBDIHCEF

### What happened?

I can't name pets, when I try and click on name pets the gui just disapears and I find this error on the console
```
[SimplePets] Task #24341 for SimplePets v5.0-BUILD-272 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'pet' in plugin SimplePets v5.0-BUILD-272
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1000) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.craftbukkit.entity.CraftPlayer.performCommand(CraftPlayer.java:769) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at SimplePets (5.0-build-272).jar/simplepets.brainsynder.menu.items.list.Name$1.run(Name.java:43) ~[SimplePets (5.0-build-272).jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_20_R2/entity/CraftPlayer
        at SimplePets (5.0-build-272).jar/simplepets.brainsynder.internal.anvil.version.Wrapper_v1_21_1.toNMS(Wrapper_v1_21_1.java:30) ~[SimplePets (5.0-build-272).jar:?]
        at SimplePets (5.0-build-272).jar/simplepets.brainsynder.internal.anvil.version.Wrapper_v1_21_1.handleInventoryCloseEvent(Wrapper_v1_21_1.java:40) ~[SimplePets (5.0-build-272).jar:?]
        at SimplePets (5.0-build-272).jar/simplepets.brainsynder.internal.anvil.AnvilGUI.openInventory(AnvilGUI.java:172) ~[SimplePets (5.0-build-272).jar:?]
        at SimplePets (5.0-build-272).jar/simplepets.brainsynder.internal.anvil.AnvilGUI.<init>(AnvilGUI.java:165) ~[SimplePets (5.0-build-272).jar:?]
        at SimplePets (5.0-build-272).jar/simplepets.brainsynder.internal.anvil.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[SimplePets (5.0-build-272).jar:?]
        at SimplePets (5.0-build-272).jar/simplepets.brainsynder.managers.RenameManager.renameViaAnvil(RenameManager.java:39) ~[SimplePets (5.0-build-272).jar:?]
        at SimplePets (5.0-build-272).jar/simplepets.brainsynder.commands.list.RenameCommand.lambda$run$0(RenameCommand.java:121) ~[SimplePets (5.0-build-272).jar:?]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at SimplePets (5.0-build-272).jar/simplepets.brainsynder.commands.list.RenameCommand.run(RenameCommand.java:87) ~[SimplePets (5.0-build-272).jar:?]
        at SimplePets (5.0-build-272).jar/lib.brainsynder.commands.ParentCommand.onCommand(ParentCommand.java:116) ~[SimplePets (5.0-build-272).jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 12 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer
        at SimplePets (5.0-build-272).jar/simplepets.brainsynder.internal.anvil.version.Wrapper_v1_21_1.toNMS(Wrapper_v1_21_1.java:30) ~[SimplePets (5.0-build-272).jar:?]
        at SimplePets (5.0-build-272).jar/simplepets.brainsynder.internal.anvil.version.Wrapper_v1_21_1.handleInventoryCloseEvent(Wrapper_v1_21_1.java:40) ~[SimplePets (5.0-build-272).jar:?]
        at SimplePets (5.0-build-272).jar/simplepets.brainsynder.internal.anvil.AnvilGUI.openInventory(AnvilGUI.java:172) ~[SimplePets (5.0-build-272).jar:?]
        at SimplePets (5.0-build-272).jar/simplepets.brainsynder.internal.anvil.AnvilGUI.<init>(AnvilGUI.java:165) ~[SimplePets (5.0-build-272).jar:?]
        at SimplePets (5.0-build-272).jar/simplepets.brainsynder.internal.anvil.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[SimplePets (5.0-build-272).jar:?]
        at SimplePets (5.0-build-272).jar/simplepets.brainsynder.managers.RenameManager.renameViaAnvil(RenameManager.java:39) ~[SimplePets (5.0-build-272).jar:?]
        at SimplePets (5.0-build-272).jar/simplepets.brainsynder.commands.list.RenameCommand.lambda$run$0(RenameCommand.java:121) ~[SimplePets (5.0-build-272).jar:?]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at SimplePets (5.0-build-272).jar/simplepets.brainsynder.commands.list.RenameCommand.run(RenameCommand.java:87) ~[SimplePets (5.0-build-272).jar:?]
        at SimplePets (5.0-build-272).jar/lib.brainsynder.commands.ParentCommand.onCommand(ParentCommand.java:116) ~[SimplePets (5.0-build-272).jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 12 more
```

### Steps To Reproduce

summon pet
click on it
click on name pet
gui disapears and error on console

### Up-To-Date

- [X] I am using the latest build

**Comment by brainsynder-Dev** [comment]
Working on a fix for this
