### ISSUE TITLE
It does not run for 1.13.1

### ISSUE THREAD

**Issue by andfont** [brainsynder-Dev/SimplePets#30]
it can not be executed in 1.13.1 and the trial versions either! Please perform a correct compilation for 1.13.1 thanks!

**Comment by Thatsmusic99** [comment]
1. You haven’t given us the server version.
2. You haven’t filled out the issue template.
3. Too vague, meaning we can’t assess this issue.

**Comment by andfont** [comment]
Sorry I give you the data:
1. Server 1.13.1
2. error is:
plugman load SimplePets
[12:34:31 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: simple/brainsynder/commands/ParentCommand
[12:34:31 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[12:34:31 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327)
[12:34:31 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:356)
[12:34:31 WARN]:        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[12:34:31 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[12:34:31 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:34:31 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[12:34:31 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699)
[12:34:31 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:684)
[12:34:31 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:459)
[12:34:31 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418)
[12:34:31 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[12:34:31 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[12:34:31 WARN]:        at java.lang.Thread.run(Thread.java:748)
[12:34:31 WARN]: Caused by: java.lang.NoClassDefFoundError: simple/brainsynder/commands/ParentCommand
[12:34:31 WARN]:        at java.lang.Class.forName0(Native Method)
[12:34:31 WARN]:        at java.lang.Class.forName(Class.java:348)
[12:34:31 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78)
[12:34:31 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[12:34:31 WARN]:        ... 13 more
[12:34:31 WARN]: Caused by: java.lang.ClassNotFoundException: simple.brainsynder.commands.ParentCommand
[12:34:31 WARN]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[12:34:31 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154)
[12:34:31 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[12:34:31 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[12:34:31 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[12:34:31 WARN]:        ... 17 more
3. It is not correctly compiled it does not find the class

Version simplepets 4.0.9
I think you have the necessary information thanks!

**Comment by brainsynder-Dev** [comment]
It does not find the class because you did not install the beta version of SimpleAPI
Available [HERE](http://ci.pluginwiki.us/job/SimpleAPI/)

**Comment by andfont** [comment]
Thank you had the previous version now if it starts but now there is no way to see the PETS do not come out? I only hear its noise that are close to me but are not visible? Why can not I see them? I am as administrator and with all the permits thank you for your attention

**Comment by Thatsmusic99** [comment]
Are you using Citizens? If so, the plugin won’t work because Citizens has the worst interference with the plugin ever and completely breaks it. I’ve been requested to contact the developers soon because it’s started to become more and more serious.

**Comment by andfont** [comment]
If I use citizen and I have never had problems, I used the echopet for 1.12 servers without problems but now with simplepets it does not work? It really is a problem friend please we are many who use citizen some temporary solution?

**Comment by andfont** [comment]
In case you are interested I have the original source code of the echopets that at the time modify it and improve it so that it works for servers 1.12.X if I want I give it to you in case it can help you improve your complement simplepets and see if there is luck and fix this problem? kind regards, friend.

**Comment by andfont** [comment]
I have reviewed the code of citizen and there is an incompatibility with simplepets in this part of the code I pass it to you, it is in the NMSImpl.java for some reason simplepets is incompatible unlike other plugins like libsdisguise, miniaturepets among others that work perfectly but for some simplepets reason does not work because of this part of the code:
@Override
    public void registerEntityClass (Class <?> clazz) {
        if (ENTITY_REGISTRY == null)
            return;

        Class <?> Search = clazz;
        while ((search = search.getSuperclass ())! = null && Entity.class.isAssignableFrom (search)) {
            EntityTypes <?> Type = ENTITY_REGISTRY.findType (search);
            MinecraftKey key = ENTITY_REGISTRY.getKey (type);
            if (key == null)
                continue;
            int code = ENTITY_REGISTRY.a (type);
            ENTITY_REGISTRY.put (code, key, type);
            return;
        }
        throw new IllegalArgumentException ("unable to find valid entity superclass for class" + clazz.toString ());
    }

Here is the problem really and why it does not work simplepets I hope it will help you to solve it, I will continue investigating greetings.!

**Comment by andfont** [comment]
modify the coding of the citizen to start 40 seconds later the main functions of NPC, then I put / pet menu and chose a pet went perfectly but then after 40 seconds the citizen had the problem in the code that I sent you I hope that it is of help for this clear that is the key, I will continue investigating greetings.

**Comment by Thatsmusic99** [comment]
If we modified that bit then I'm pretty sure Citizens wouldn't register its own entities. However I will double check a lot of that...

**Comment by brainsynder-Dev** [comment]
This has been fixed in the latest Development build, Please download it from the [JENKINS](http://ci.pluginwiki.us/job/SimplePets/) page
