### ISSUE TITLE
"Pet" command not working.

### ISSUE THREAD

**Issue by jayjoejeans** [brainsynder-Dev/SimplePets#31]
When I try the command "pet" it says this in cmd.

org.bukkit.command.CommandException: Cannot execute command 'pet' in plugin SimplePets v4.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[craftbukkit-1.13.2.jar:git-Bukkit-3359cb1]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.13.2.jar:git-Bukkit-3359cb1]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:679) ~[craftbukkit-1.13.2.jar:git-Bukkit-3359cb1]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:665) [craftbukkit-1.13.2.jar:git-Bukkit-3359cb1]
        at net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:423) [craftbukkit-1.13.2.jar:git-Bukkit-3359cb1]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:383) [craftbukkit-1.13.2.jar:git-Bukkit-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:796) [craftbukkit-1.13.2.jar:git-Bukkit-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:699) [craftbukkit-1.13.2.jar:git-Bukkit-3359cb1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]

Help?

**Comment by Thatsmusic99** [comment]
Please try the development builds for SimpleAPI and SimplePets. v4.0 does not support 1.13.x.

SimplePets: http://ci.pluginwiki.us/job/SimplePets/
SimpleAPI (there may be a different build but here’s the one I know of currently): https://cdn.discordapp.com/attachments/269172690957369355/486075426872229900/SimpleAPI.jar

**Comment by jayjoejeans** [comment]
> Please try the development builds for SimpleAPI and SimplePets. v4.0 does not support 1.13.x.
> 
> SimplePets: http://ci.pluginwiki.us/job/SimplePets/
> SimpleAPI (there may be a different build but here’s the one I know of currently): https://cdn.discordapp.com/attachments/269172690957369355/486075426872229900/SimpleAPI.jar

I downloaded the new builds and it still doesn't work.

**Comment by brainsynder-Dev** [comment]
[SimpleAPI](http://ci.pluginwiki.us/job/SimpleAPI/lastSuccessfulBuild/artifact/target/SimpleAPI.jar)
[SimplePets](http://ci.pluginwiki.us/job/SimplePets/lastSuccessfulBuild/artifact/DIST/target/SimplePets.jar)

and be sure to restart your server (not reload, as that can cause more issues)

**Comment by jayjoejeans** [comment]
[latest.log](https://github.com/brainsynder-Dev/SimplePets/files/2526591/latest.log)

**Comment by brainsynder-Dev** [comment]
Ahhhhh let me guess.... you are using Bukkit/CraftBukkit...

If so that is why... you need to use a version of Spigot... (That includes all the forks of Spigot like PaperSpigot... ETC)

**Comment by jayjoejeans** [comment]
OOOHHHH. Thank you!
