### ISSUE TITLE
Random NPE in console

### ISSUE THREAD

**Issue by bloggy** [brainsynder-Dev/SimplePets#37]
SimplePets 4.1-RELEASE
SimpleAPI v3.8-SNAPSHOT

Error in console:

```
[14:37:05] [Craft Scheduler Thread - 258/WARN]: [SimpleAPI] Plugin SimpleAPI v3.8-SNAPSHOT generated an exception while executing task 999
java.lang.NoClassDefFoundError: me/zombie_striker/pluginconstructor/privatemetrics/Metrics$CustomChart
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_121]
	at java.lang.Class.privateGetMethodRecursive(Unknown Source) ~[?:1.8.0_121]
	at java.lang.Class.getMethod0(Unknown Source) ~[?:1.8.0_121]
	at java.lang.Class.getMethod(Unknown Source) ~[?:1.8.0_121]
	at simple.brainsynder.utils.SpigotPluginHandler$BStats.submitData(SpigotPluginHandler.java:686) ~[?:?]
	at simple.brainsynder.utils.SpigotPluginHandler$BStats.access$600(SpigotPluginHandler.java:490) ~[?:?]
	at simple.brainsynder.utils.SpigotPluginHandler$BStats$1.lambda$run$0(SpigotPluginHandler.java:598) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-525]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-525]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: me.zombie_striker.pluginconstructor.privatemetrics.Metrics$CustomChart
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-525]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	... 14 more
```

**Comment by brainsynder-Dev** [comment]
This bug report Should have been posted on the SimpleAPI Github not SimplePets... Anyway...
`me/zombie_striker/pluginconstructor/privatemetrics/Metrics` is not a part of SimpleAPI
So which ever plugin has a class like that is causing the issue.
