### ISSUE TITLE
Rename Pet NPE

### ISSUE THREAD

**Issue by bloggy** [brainsynder-Dev/SimplePets#39]
Renaming a pet in the anvil can cause NPE when player clicks on the anvil result slot:
https://i.imgur.com/AG7aca4.png

Error in console:

```
[13:31:15 WARN]: Entity threw exception at Adminwelt:1043.4848987934024,70.0,-6194.50908022597
[13:31:15 WARN]: java.lang.NullPointerException
[13:31:15 WARN]: at simplepets.brainsynder.nms.v1_13_R2.entities.list.EntityControllerPet.repeatTask(EntityControllerPet.java:166)
[13:31:15 WARN]: at simplepets.brainsynder.nms.v1_13_R2.entities.EntityPet.W(EntityPet.java:464)
[13:31:15 WARN]: at net.minecraft.server.v1_13_R2.Entity.tick(Entity.java:355)
[13:31:15 WARN]: at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2103)
[13:31:15 WARN]: at net.minecraft.server.v1_13_R2.EntityInsentient.tick(EntityInsentient.java:261)
[13:31:15 WARN]: at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1568)
[13:31:15 WARN]: at net.minecraft.server.v1_13_R2.World.g(World.java:1535)
[13:31:15 WARN]: at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1342)
[13:31:15 WARN]: at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:598)
[13:31:15 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1100)
[13:31:15 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[13:31:15 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[13:31:15 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[13:31:15 WARN]: at java.lang.Thread.run(Thread.java:748)
```
Using latest dev build of your plugin

**Comment by brainsynder-Dev** [comment]
I will look into this  issue.
