### ISSUE TITLE
PlotSquared v4 class name changes

### ISSUE THREAD

**Issue by dextonanderson** [brainsynder-Dev/SimplePets#45]
### What steps will reproduce the problem?
1. Install SimplePets with PlotSquared v4 (1.13+)
2. Try and use SimplePets on a plot

### What were you expecting to happen? 
Pets spawn as normal on a plot
### What happened instead?
Pets do not spawn

In PlotSquared v4, the `PS` class was renamed to `PlotSquared`, SimplePets does not handle this and thus:

```[13:57:20 WARN]: [SimplePets] Task #18498 for SimplePets v4.1-RELEASE generated an exception
java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/PS
        at simplepets.brainsynder.links.impl.PlotSquaredLink.fetchValue(PlotSquaredLink.java:46) ~[?:?]
        at simplepets.brainsynder.links.impl.PlotSquaredLink.allowPetSpawn(PlotSquaredLink.java:26) ~[?:?]
        at simplepets.brainsynder.links.impl.PlotSquaredLink.allowPetSpawn(PlotSquaredLink.java:41) ~[?:?]
        at simplepets.brainsynder.links.LinkRetriever.canSpawnPet(LinkRetriever.java:86) ~[?:?]
        at simplepets.brainsynder.links.LinkRetriever.canSpawnPet(LinkRetriever.java:43) ~[?:?]
        at simplepets.brainsynder.pet.Pet.<init>(Pet.java:62) ~[?:?]
        at simplepets.brainsynder.pet.PetDefault.setPet(PetDefault.java:67) ~[?:?]
        at simplepets.brainsynder.menu.inventory.listeners.SelectionListener$1.run(SelectionListener.java:57) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

It also seems like there was an attempt at using the new PlotSquared package names, however this seems to not take effect on 1.13.2.

https://github.com/brainsynder-Dev/SimplePets/blob/548bfa38dcfc8096397d0dd1a2b9fc9d089aeb09/MAIN/src/main/java/simplepets/brainsynder/links/impl/PlotSquaredLink.java#L34

**Edit: It would seem this should actually work, but for some reason SimplePets thinks I am not running PlotSquared v4**

**Comment by Thatsmusic99** [comment]
SuperMonis brought this up to me. Please try using the latest dev builds: http://ci.pluginwiki.us/job/SimplePets/27/

**Comment by dextonanderson** [comment]
Will do, I had downloaded the latest off of the website.

```> ver simplepets
[14:05:58 INFO]: SimplePets version 4.1-RELEASE
[14:05:58 INFO]: Authors: brainsynder and Thatsmusic99
```

**Comment by dextonanderson** [comment]
Works, thanks.
