### ISSUE TITLE
Adapter for PlotSquared is not up to date. 

### ISSUE THREAD

**Issue by yannicklamprecht** [brainsynder-Dev/SimplePets#50]
```
[00:07:09] [Server thread/WARN]: [SimplePets] Task #114132 for SimplePets v4.1-RELEASE generated an exception
java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/PS
	at simplepets.brainsynder.links.impl.PlotSquaredLink.fetchValue(PlotSquaredLink.java:46) ~[?:?]
	at simplepets.brainsynder.links.impl.PlotSquaredLink.allowPetSpawn(PlotSquaredLink.java:26) ~[?:?]
	at simplepets.brainsynder.links.impl.PlotSquaredLink.allowPetSpawn(PlotSquaredLink.java:41) ~[?:?]
	at simplepets.brainsynder.links.LinkRetriever.canSpawnPet(LinkRetriever.java:86) ~[?:?]
	at simplepets.brainsynder.links.LinkRetriever.canSpawnPet(LinkRetriever.java:43) ~[?:?]
	at simplepets.brainsynder.pet.Pet.<init>(Pet.java:62) ~[?:?]
	at simplepets.brainsynder.pet.PetDefault.setPet(PetDefault.java:67) ~[?:?]
	at simplepets.brainsynder.menu.inventory.listeners.SelectionListener$1.run(SelectionListener.java:57) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-641]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-641]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-641]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-641]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-641]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-641]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

Adapter for PlotSquared is not up to date. 

https://github.com/brainsynder-Dev/SimplePets/blob/master/MAIN/src/main/java/simplepets/brainsynder/links/impl/PlotSquaredLink.java

**Comment by Thatsmusic99** [comment]
In the bug report format, it asked if you tried one of the development builds. This was already fixed in the builds (please use both SimplePets and SimpleAPI):

https://cdn.discordapp.com/attachments/269172690957369355/614824378936590387/SimplePets.jar
https://cdn.discordapp.com/attachments/479339886474952705/580825981271670784/SimpleAPI.jar
